trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: DotNetCoreCLI@2
  displayName: 'Build Package'
  inputs:
    command: 'pack'
    projects: 'src/ExcelFinancialFunctions/*.fsproj'
    arguments: '--output $(System.DefaultWorkingDirectory)/publish_output --configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: 'tests/ExcelFinancialFunctions.Tests/*.fsproj'
  
- publish: $(Build.ArtifactStagingDirectory)/publish_output/*.nupkg
  artifact: drop