trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'src/*/*.fsproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: 'tests/ExcelFinancialFunctions.Tests/*.fsproj'

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/*/*.fsproj'
    configuration: 'Release'
    versioningScheme: 'off'
    verbosityPack: 'Normal'

- task: PublishBuildArtifacts@1
  displayName: 'Publish'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'package'
    publishLocation: 'Container'