trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: DotNetCoreCLI@2
  displayName: 'Build Package'
  inputs:
    command: 'pack'
    packagesToPack: 'src/*/*.fsproj'
    configuration: 'Release'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: 'tests/ExcelFinancialFunctions.Tests/*.fsproj'