trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: 'tests/ExcelFinancialFunctions.Tests/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Package'
  inputs:
    command: 'pack'
    arguments: '--output $(System.DefaultWorkingDirectory)/publish_output --configuration Release'
    projects: 'src/*/*.csproj'
  
- publish: $(Build.ArtifactStagingDirectory)/publish_output/*.nupkg
  artifact: drop